import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReactNode } from "react";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
//import { QueryClient, QueryClientProvider } from "@tanstack/react-query";


const inter = Inter({ subsets: ['latin'] })
//const queryClient = new QueryClient();

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>orderjoy-bot</title>
        <meta name="description" content="Lovable Generated Project" />
        <meta name="author" content="Lovable" />
        <meta property="og:image" content="/og-image.png" />
      </head>
      <body>
        {/* <QueryClientProvider client={queryClient}> */}
          <TooltipProvider>
            <Toaster />
            <Sonner />
            {children}
            {/* IMPORTANT: DO NOT REMOVE THIS SCRIPT TAG OR THIS VERY COMMENT! */}
            <script
              src="https://cdn.gpteng.co/gptengineer.js"
              type="module"
            ></script>
            <script type="module" src="/src/main.tsx"></script>
          </TooltipProvider>
      </body>
    </html>
  );
}
